### Get sheet all cell values
### 200
GET  http://localhost:45001/api/v1/sheet1
### 404
GET  http://localhost:45001/api/v1/sheet2

### Get sheet cell value
### 200
GET  http://localhost:45001/api/v1/sheet1/var1
### 404
GET  http://localhost:45001/api/v1/sheet1/var999


### 201
POST  http://localhost:45001/api/v1/sheet1/var3
Content-Type: application/json

{
  "value": "=var1+var2"
}